### PR TITLE
[Fix #37] Correct the binding and test with modern ClojureScript

### LINKED ISSUE #37: Possible breakage with ClojureScript 1.10.439
Hello!

I have noticed some possible breakage with the new ClojureScript `1.10.439`. The way humane pretty prints the diff will likely break. I have not tried but I am copying that piece of code somewhere around here as well and it broke :smile: 

The repro looks like this:

```clojure
[Rebel readline] Type :repl/help for online help info
cljs.user=> (require '[cljs.pprint :as pprint])
cljs.user=> (require '[goog.string :as gstring])
cljs.user=> (import '[goog.string StringBuffer])
nil
cljs.user=> (defn with-pretty-writer* [f]
       #_=>   (binding [*sb* (StringBuffer.)
       #_=>             *out* (pprint/get-pretty-writer (StringBufferWriter. *sb*))]
       #_=>     (f)))

#'cljs.user/write*
cljs.user=> (defn- write* [s]
       #_=>   (cljs.core/-write cljs.core/*out* s))

cljs.user=> (with-pretty-writer* #(write* "test"))
TypeError: Cannot read property "append" from undefined
	 cljs$core$IWriter$_write$arity$2 (.cljs_nashorn_repl/cljs/core.cljs:874:17)
	 cljs$core$_write (.cljs_nashorn_repl/cljs/core.cljs:750:1)
	 <anonymous> (.cljs_nashorn_repl/cljs/pprint.cljs:212:14)
	 cljs.core/-write (.cljs_nashorn_repl/cljs/core.cljs:750:1)
	 <anonymous> (.cljs_nashorn_repl/cljs/pprint.cljs:525:18)
	 cljs$core$_write (.cljs_nashorn_repl/cljs/core.cljs:750:1)
	 (<NO_SOURCE_FILE> <eval>:3:0)
	 (<NO_SOURCE_FILE> <eval>:2:0)
	 (<NO_SOURCE_FILE> <eval>:11:0)
	 (<NO_SOURCE_FILE> <eval>:1:0)
	 (<NO_SOURCE_FILE> <eval>:1:0)
	 (<NO_SOURCE_FILE> <eval>:1:0)
```

I will try to put together a fix but can't promise and of course we are on our own for using the `binding` that way :smile:

### PR DESCRIPTION
**Pull request by arichiardi**
This change is necessary in order to test against the newer ClojureScript
versions. In particular since version 1.10.439 it is not possible to bind a
dynamic var and use it in the same binding form.

Additionally, the old way of testing with phantom js was broken with the new
ClojureScript so this patch moves to a more modern setup using lein-doo.

### CODE REVIEW

**Comment by arichiardi** [comment]
Oh Travis is not running here?

**Comment by pjstadig** [comment]
@arichiardi I turned on Travis. Would you mind looking at the output from the failure?

**Comment by arichiardi** [comment]
Will certainly do

**Comment by nenadalm** [comment]
build fixed here: https://github.com/pjstadig/humane-test-output/pull/40

**Comment by pesterhazy** [comment]
It would be great to see this merged, as the compiler warnings (as in #37) can be confusing

**Comment by pesterhazy** [comment]
Thanks! I appreciate it

**Comment by arichiardi** [comment]
Great!

**Pull request merged**
