### PR TITLE
Check number of arguments to = at read time

### LINKED ISSUE #20: Bad interaction with eastwood
When humane-test-output has been injected, the overwritten `=` method on `assert-expr` triggers nuisance warnings from the [eastwood](https://github.com/jonase/eastwood) static analysis tool. The warnings look like this.

```
test/honeysql/format_test.clj:89:3: constant-test: Test expression is always logical true or always logical false: (clojure.core/seq (clojure.core/list ["SELECT foo FROM bar1 UNION SELECT foo FROM bar2"])) in form (if temp__4655__auto__ (clojure.core/let [more__35__auto__ temp__4655__auto__] (clojure.core/let [result__36__auto__ (clojure.core/apply clojure.core/= a__34__auto__ more__35__auto__)] (if result__36__auto__ (clojure.test/do-report {:type :pass, :expected a__34__auto__, :actual more__35__auto__, :message nil}) (clojure.test/do-report {:type :fail, :diffs (clojure.core/map clojure.core/vector more__35__auto__ (clojure.core/map (fn* [p1__33__37__auto__] (clojure.core/take 2 (clojure.data/diff a__34__auto__ p1__33__37__auto__))) more__35__auto__)), :expected a__34__auto__, :actual more__35__auto__, :message nil})) result__36__auto__)) (throw (java.lang.Exception. "= expects more than one argument")))
```

I think this is happening because the new `=` method is checking the number of arguments at run time, and conditionally throwing based on that. Eastwood is (correctly) detecting that this check is looking at a constant vector. If this check were moved outside of the syntax quote, and the check and exception were done at macro expansion time, then these nuisance warnings would go away, and h-t-o would detect these typos earlier in the process.

CC @MichaelBlume

### PR DESCRIPTION
**Pull request by divergentdave**
This fixes #20 by checking the number of macro arguments at read time

### CODE REVIEW

**Comment by pjstadig** [comment]
Looks good to me. Thanks!

**Comment by pjstadig** [comment]
Sorry, I was just noticing one thing. There's also a `=-body` in `pjstadig.assert-expr` which is the CLJS side of things. Do we have the same concern/problem CLJS side? If so we should probably update that as well. I'd actually rather see them merged together, if possible.

**Comment by pjstadig** [comment]
I can take a look at it. It might be a good opportunity to clean up some code, but I may not be able to get to this weekend.

**Comment by divergentdave** [comment]
Yeah, looks like the same thing can be done there. It's a bit more
academic, because eastwood does not yet support CLJS, but :+1: from me.

**Comment by pjstadig** [comment]
I went ahead and released version 0.8.1 with your change. Cheers!

**Pull request merged**
