### PR TITLE
Use lambdaisland.deep-diff instead of clojure.data/diff

### PR DESCRIPTION
**Pull request by ghost**
image

https://github.com/lambdaisland/deep-diff

Quick and dirty, sorry. Consider this more like an issue than a PR. Feel free to close.

### CODE REVIEW

**Comment by arichiardi** [comment]
Wow that's very cool! 

Me like it :smile: is it Cljs compatible as well?

**Comment by plexus** [comment]
@arichiardi no, it uses [clj-diff](https://github.com/brentonashworth/clj-diff) for diffing sequences, and that one seems to be JVM only. Not sure about the other dependencies. I guess Puget and Fipp are cross platform. Not sure about arrangement.

This has been extracted from Kaocha which is JVM only, so it wasn't really an issue there. Would be cool to port it though.

**Comment by TristeFigure** [comment]
• Arrangement: supports cljs.
• Puget: There is a WIP pull request for that: https://github.com/greglook/puget/pull/30. Incidentally it awaits cljs support in arrangement (which is done but has not yet been propagated to this PR).
• Fipp: support cljs.
• Clj-diff: There is a WIP pull request for that: https://github.com/brentonashworth/clj-diff/pull/5/files. Seems to work but lacks a cljs test-suite. The PR is old and the owner has not reacted to it.

@plexus : Someone suggested you editscript on slack and I have noticed your recent commit on the README fo deep-diff. Is there any reason you might want to adopt editscript beyond cljs support ?

Also, congrats for the grant you received for your work on Kaocha ! I would be pleased to save you some time by orchestrating the PRs listed above.

**Comment by TristeFigure** [comment]
There are now notifications on the two PRs above about the fact they are now linked to this one. Wait and see...

**Comment by plexus** [comment]
Thanks for checking out the upstream dependencies. I added an issue on deep-diff: https://github.com/lambdaisland/deep-diff/issues/2 for people that are also wondering about CLJS support.

> Is there any reason you might want to adopt editscript beyond cljs support ?

I wasn't aware of editscript before writing deep-diff. It might or might not be a better diffing backend than cj-diff, but switching to it would mean a complete rewrite of `lambdaisland.deep-diff.diff`, which I don't think is the best use of my time right now. I added it to the README so I could find it again if I ever want to look at it, but I don't plan to do much with it right now.

**Comment by pjstadig** [comment]
I don't want to rely on coloring to tell what has been added and what has been removed. Aside from coloring, '+' and '-' added to the front of numbers can be ambiguous as to whether the number is being added or removed or just happens to be a negative number. The '+' added to the front of `:c` indicates that the entire pair has been added? I find it a bit difficult to decipher, but maybe I'm just not used to it?

Not that the existing output couldn't be improved in some way, but unless it turns out that most people would prefer this, I'm inclined to keep it the same. Sorry!

**Pull request closed without merging**
