### PR TITLE
inspect `actual` instead of defmethod-ing assert-expr

### PR DESCRIPTION
**Pull request by ryfow**
I've had some weird issues with the assert-expr overrides not working in all circumstances. I'm not really sure why I'm having that problem but when I started digging into it, I noticed that I could just run the diff on the data structure clojure.test reports.

Thought you might be interested in seeing the results.

If you're interested in moving to an approach like this, I'll do some work on cleaning up the implementation.

### CODE REVIEW

**Comment by pjstadig** [comment]
Yeah this is not a bad approach. Now that the ClojureScript changes are in, I don't know if that changes anything? Would a similar approach be possible with ClojureScript?

I hate to ask for something to be done speculatively, but I wouldn't mind seeing a cleaned up implementation. If this could lead to better testability (instead of having to manually or automatically inspect the test output, then that may not be so bad either.

**Comment by ryfow** [comment]
I rebased, extracted convert-event, and added cljs. Seems to work, I'll use it personally for a while to confirm. Having `convert-event` and `report-` separate should make testing slightly simpler.

That `(when)` test in `convert-event` is still nasty, but I'm not sure how to make it better and don't have time to mess with it right now.

**Comment by ryfow** [comment]
BTW, you lose the "bonus feature" of warning about `(= "one arg")`.

**Comment by pjstadig** [comment]
:/ I'm not so happy about losing my bonus feature!

**Comment by arichiardi** [comment]
This patch is definitely interesting, I will try it out as well here in lumo.

**Comment by arichiardi** [comment]
I switched to this branch and magically `lumo` perfectly works!

```clojure
$ lumo -c $(lein with-profile +dev, classpath) -sfK -e '(require (quote pjstadig.run-all))' -e '(pjstadig.run-all/run)'

Testing pjstadig.humane-test-output.formatting-test

FAIL in (t-formatting) (at evalmachine.<anonymous>:439:83)
THESE TESTS ARE INTENDED TO FAIL
expected: {:foo :bar,
           :baz :quux,
           :something "a long string?",
           :another-key "and another value"}
  actual: {:fo :bar}

    diff: - {:foo :bar,
             :baz :quux,
             :something "a long string?",
             :another-key "and another value"}
          + {:fo :bar}
```

**Comment by arichiardi** [comment]
The only change I made was to get rid of `include-macros` for `clojure.data` (no macros in there)

**Comment by pjstadig** [comment]
It's possible this has fewer interactions with IDEs and such, but I feel like we're reimplementing `assert-expr` by inspecting the form and then deciding what to do. I also don't want to lose my bonus feature. I made some more extensive comments on #27 about what changes I think would be helpful. I think I'd like to see those things taken care of before taking on other things.

I do appreciate the feedback and submitting PRs. I apologize for being so slow to respond, but my non-open-source life is a bit crazy. I don't want people to feel like they have wasted their time, so hopefully what I've outlined in #27 will give people a direction that will more likely result in a PR being merged.

**Pull request closed without merging**
