### PR TITLE
Alternative, self-host compatible ClojureScript implementation

### PR DESCRIPTION
**Pull request by arichiardi**
This patch slightly modifies #27 so that ClojureScript gets the new
implementation.

The motivation is that the differences in how vars and macros work in Cljs, the
current way is brittle and also not compatible with self-host solutions like
`lumo`.

The downside of this approach is that the bonus feature - throwing in case of
one argument only to clojure.test/is - is dropped.

Most of the work was done by @ryfow and I am just ~hammering it in~ massage it
in.

### CODE REVIEW

**Comment by arichiardi** [comment]
I would probably squash this one into one commit whenever is ready, leaving it there for now as it is to understand the history :smile:

**Comment by arichiardi** [comment]
WIP because I have to clean some stuff up in the Clojure impl that should be left untouched.

**Comment by arichiardi** [comment]
@pjstadig this is now ready, I have tested with the two commands in `.travis.yml` and they both succeed

The only test that fails in `lumo` land is the one added by @ryfow.

It can be tried with:

```
$lumo -c $(lein classpath) -i test/pjstadig/run_all.cljs -e '(pjstadig.run-all/run)' | diff test/fixtures/test_output_cljs -

> FAIL in (t-macro-wrapping) (at evalmachine.<anonymous>:439:83)
80,84c78,79
< expected: 1
<   actual: 2
< 
<     diff: - 1
<           + 2
---
> expected: (cljs.core/= 1 2)
>   actual: (not (cljs.core/= 1 2))

```

I think I need some help on understanding what it tests I guess...

**Comment by arichiardi** [comment]
I also added the `lumo` tests in `.travis.yml`

**Comment by pjstadig** [comment]
@arichiardi that test is there because when an assertion is part of a macro, all the symbols get fully qualified. As a result we need to override the behavior for both `=` and `clojure.core/=` in `assert-expr`. I guess the same is true for `cljs.core/=`?

**Comment by arichiardi** [comment]
Uhm I thought that the new patch for cljs did not override the equality functions, but was comparing and diffing within the test failure handler. I will confirm this to you as soon as I get some time

**Comment by arichiardi** [comment]
Ok fixed the `cljs.core/=` test  - ClojureScript seems to be good now ;) No changes to Clojure.

I also discovered that the JVM ClojureScript tests are not running anymore and reported it in an issue because there should probably be a separate patch for that.

**Pull request merged**
